### ISSUE TITLE
Realworld API spec (task) checklist

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakephp-realworld-backend#1]
Please reference to this ticket when creating a related ticket/PR.

- [ ] Articles
  - [ ] GET - Feed
  - [ ] GET - All articles
  - [ ] GET - Articles by author
  - [ ] GET - Articles favorited by username
  - [ ] GET - Articles by tag
  - [ ] POST - Create article
  - [ ] GET - Single article by slug
  - [ ] DEL - Delete article
  - [ ] PUT - Update article
  - [ ] POST - Favorite article
  - [ ] DEL - Unfavorite article

- [ ] Auth
  - [ ] POST - Login
  - [ ] POST - Login and remember token
  - [ ] POST - Register
  - [ ] GET - Get current user
  - [ ] PUT - Update user

- [ ] Comments
  - [ ] GET - All comments for article
  - [ ] POST - Create comment for article
  - [ ] DEL - Delete comment

- [ ] Comments
  - [ ] GET - Profile
  - [ ] POST - Follow profile
  - [ ] DEL - Unfollow profile

- [ ] Comments
  - [ ] GET - Get all tags
